### ISSUE TITLE
Nuget package version

### ISSUE THREAD

**Issue by kingsimmy** [hughbe/html-generator#6]
Hi @hughbe 

Would it be possible for you to upload a build of the latest code to Nuget?

Thanks,

**Comment by hughbe** [comment]
@kingsimmy 
Hi,
I'm having some really weird problems with nuget/VS: nothing is the same as it was when I released the project, and I have no idea how to build a nuget project from xproj anymore. Google isn't helping either!

Do you have any pointers? If you can build the .nupkg package, I can upload it!

**Comment by hughbe** [comment]
Update:
I did it!! I had to run `dotnet pack` instead of `nuget pack`

Will upload shortly

**Comment by kingsimmy** [comment]
Awesome, thanks!

**Comment by hughbe** [comment]
Should be up - Version 1.0.13

Sorry for the delay.
